export const KBO_TEAMS = [
  {
    id: 'doosan',
    name: '두산 베어스',
    shortName: '두산',
    emoji: '🐻',
    logo: 'BEARS',
    primaryColor: '#131230',
    secondaryColor: '#EA0029',
    gradient: 'from-[#131230] to-[#EA0029]',
    lightGradient: 'from-slate-700 to-rose-600',
  },
  {
    id: 'lg',
    name: 'LG 트윈스',
    shortName: 'LG',
    emoji: '⚾',
    logo: 'LG',
    primaryColor: '#C30452',
    secondaryColor: '#000000',
    gradient: 'from-[#C30452] to-[#000000]',
    lightGradient: 'from-pink-700 to-slate-800',
  },
  {
    id: 'kiwoom',
    name: '키움 히어로즈',
    shortName: '키움',
    emoji: '🦸',
    logo: 'HEROES',
    primaryColor: '#820024',
    secondaryColor: '#000000',
    gradient: 'from-[#820024] to-[#000000]',
    lightGradient: 'from-rose-800 to-slate-800',
  },
  {
    id: 'kt',
    name: 'KT 위즈',
    shortName: 'KT',
    emoji: '🧙',
    logo: 'KT',
    primaryColor: '#000000',
    secondaryColor: '#EA0029',
    gradient: 'from-[#000000] to-[#EA0029]',
    lightGradient: 'from-slate-800 to-rose-600',
  },
  {
    id: 'ssg',
    name: 'SSG 랜더스',
    shortName: 'SSG',
    emoji: '⚡',
    logo: 'SSG',
    primaryColor: '#CE0E2D',
    secondaryColor: '#003B5C',
    gradient: 'from-[#CE0E2D] to-[#003B5C]',
    lightGradient: 'from-rose-600 to-blue-900',
  },
  {
    id: 'lotte',
    name: '롯데 자이언츠',
    shortName: '롯데',
    emoji: '⭐',
    logo: 'LOTTE',
    primaryColor: '#041E42',
    secondaryColor: '#D00F31',
    gradient: 'from-[#041E42] to-[#D00F31]',
    lightGradient: 'from-blue-900 to-rose-600',
  },
  {
    id: 'samsung',
    name: '삼성 라이온즈',
    shortName: '삼성',
    emoji: '🦁',
    logo: 'LIONS',
    primaryColor: '#074CA1',
    secondaryColor: '#1C63B7',
    gradient: 'from-[#074CA1] to-[#1C63B7]',
    lightGradient: 'from-blue-700 to-blue-600',
  },
  {
    id: 'nc',
    name: 'NC 다이노스',
    shortName: 'NC',
    emoji: '🦖',
    logo: 'NC',
    primaryColor: '#315288',
    secondaryColor: '#B99B61',
    gradient: 'from-[#315288] to-[#B99B61]',
    lightGradient: 'from-blue-800 to-amber-600',
  },
  {
    id: 'hanwha',
    name: '한화 이글스',
    shortName: '한화',
    emoji: '🦅',
    logo: 'EAGLES',
    primaryColor: '#FF6600',
    secondaryColor: '#000000',
    gradient: 'from-[#FF6600] to-[#000000]',
    lightGradient: 'from-orange-500 to-slate-800',
  },
  {
    id: 'kia',
    name: 'KIA 타이거즈',
    shortName: 'KIA',
    emoji: '🐯',
    logo: 'TIGERS',
    primaryColor: '#EA0029',
    secondaryColor: '#000000',
    gradient: 'from-[#EA0029] to-[#000000]',
    lightGradient: 'from-rose-600 to-slate-800',
  },
];
